site_name: Gillian's GTA IV Guide
plugins:
  - i18n:
      default_language: en
      languages:
        en:
          name: English
        ru:
          name: Русский
  - glightbox
  - social:
    definitions:
    - &page_title_with_site_name >-
      {%- if not page.is_homepage -%}
        {{ page.meta.get("title", page.title) }} - {{ config.site_name }}
      {%- else -%}
        {{ page.meta.get("title", page.title) }}
      {%- endif -%}

    - &page_description >-
      {{ page.meta.get("description", config.site_description) or "" }}

  tags:
    og:type: website
    og:title: *page_title_with_site_name
    og:description: *page_description
    og:image: "{{ image.url }}"
    og:image:type: "{{ image.type }}"
    og:image:width: "{{ image.width }}"
    og:image:height: "{{ image.height }}"
    og:url: "{{ page.canonical_url }}"

    twitter:card: summary_large_image
    twitter.title: *page_title_with_site_name
    twitter:description: *page_description
    twitter:image: "{{ image.url }}"
        
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - toc.integrate
    - content.tabs.link
    - navigation.instant
    - navigation.expand
markdown_extensions:
  - md_in_html
  - admonition
  - tables
  - attr_list
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - "index.md"
  - "Drag-and-Drop-Archive.md"
  - "Main-Optimisation.md"
  - "Additional-Setup.md"
  - "downgrading.md"
  - Essential Modding:
    - "Essential-Modding/index.md"
    - "Essential-Modding/FusionFix.md"
    - "Essential-Modding/ZolikaPatch.md"
    - "Essential-Modding/Shader-Fixes.md"
  - "multiplayer.md"

extra:
  analytics:
    provider: google
    property: G-RSQFR3F839
  consent:
    title: Cookie consent
    description: >- 
      I use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of my guide and whether users
      find what they're searching for. With your consent, you're helping me to
      make my guide better.
